export const ADD_TO_CART = 'ADD_TO_CART'
export const ADD_COUNT = 'ADD_COUNT'
export const DEDUCT_COUNT = 'DEDUCT_COUNT'
export const SELECT_GOODS = 'SELECT_GOODS'
export const SELECT_ALL_GOODS = 'SELECT_ALL_GOODS'
