export const ADD_TO_CART = 'ADD_TO_CART';  // 添加到购物车
export const ADD_COUNT = 'ADD_COUNT';  // 商品数量加
export const DEDUCT_COUNT = 'DEDUCT_COUNT';  // 商品数量减
export const SELECT_GOODS = 'SELECT_GOODS';  // 选择商品
export const SELECT_ALL_GOODS = 'SELECT_ALL_GOODS';  // 商品全选
export const ADD_ADDRESS = 'ADD_ADDRESS';  // 添加地址
export const DELETE_ADDRESS = 'DELETE_ADDRESS'; // 删除地址
export const UPDATE_ADDRESS = 'UPDATE_ADDRESS';  // 更新地址
export const ADD_COLLECTON = 'ADD_COLLECTON';  // 添加收藏
export const DELETE_COLLECTON = 'DELETE_COLLECTON'; 